### ISSUE TITLE
1.6 TODO

### ISSUE THREAD

**Issue by IntegerLimit** [Nomi-CEu/nomi-ceu#302]
- [x] Move NM PBF removals to removeAll. See https://github.com/GregTechCEu/GregTech/pull/1625.
- [x] Addition of https://www.curseforge.com/minecraft/mc-mods/natures-compass/
- [x] Addition of https://www.curseforge.com/minecraft/mc-mods/betterp2p/ 
- [x] Look at how to remove ways to get pulverised obsidian + niter, also add conversion recipes
- [x] Cow Soul Vial -> Cow Spawn Egg recipe
- [x] Change Storage Drawer's config to make it so that drawers do not drop items on break
- [x] Quests for P2P and Nature's Compass
- [x] Backups to be default 30min.
- [x] Rename EU P2p from GTEU -> EU
- [x] Add tooltip on EU P2P of how it is made (any gt wire, maybe cable?)
- [x] Add tooltip to ME p2p, saying it is the base or something 
- [x] Mention Storage Drawers Keys in qb, and how they can affect a whole array with controllers.
- [x] Replace phosphor with https://www.curseforge.com/minecraft/mc-mods/hesperus
- [x] Quest for Sorting stuff
- [x] RHF and BBC remove assembler recipes, NM change to ZPM
- [x] Main Menu Screenshots
- [x] Gregtech 2.6 (ofc).
