### ISSUE TITLE
1.6.1 TODO

### ISSUE THREAD

**Issue by IntegerLimit** [Nomi-CEu/Nomi-CEu#323]
- [x] Quest for the EIO Spawner
- [x] Rotate HM Early Game 90 degrees
- [x] Undo Fix BlastFurnace.zs NPE commit when GCYM patch comes out, fixing it, and furthermore, adding back ABS recipes for various alloys, such as vanadiumsteel, energetic alloy, and vibrant alloy
- [x] Fix BlastFurnace.zs NPE
- [x] Clear up bogosorter quest, with info about hovering over inventory slots to sort them
- [x] Dstillation Tower qb HM requires Iridium
- [x] Tier two micro miner qb may not require boron
- [x] Wiremill quest should give circuit, instead of bender quest
- [x] Get a GT and GCYM patch, fixing ABS recipe issues and GT PAs in cleanrooms issue
- [x] Fix recycling recipes of RBF and BBC, as well as hv dynamo maybe (NM, check HM)
- [x] Balance Caesium [HM]
- [x] Make Cleanroom Quest Clearer
- [x] Update BogoSort to 1.2.7, remove qb part on rebinding sort keybind (middle click works now)
- [x] Update AE2 UEL
- [x] Update HEI
- [x] Fix https://github.com/GregTechCEu/GregTech/issues/1674
- [x] Get an update of ULV covers or maybe gt to fix crash
- [x] Improve material tab quest description
- [x] Update Rotary Hearth Furnace parallel description in qb
- [x] https://github.com/Nomi-CEu/nomi-ceu/issues/367 most qb stuff

**Comment by Folanlron** [comment]
Chemical Reactor Recipe for Rocket Fuel, needs to be set as a Large Chemical Reactor recipe only as the Fluid output for the Fuel is 18buckets/recipe with using Hydrazine.

**Comment by Folanlron** [comment]
On Beta2(Not sure if this also applies to beta1)

- [ ]  NM Mixer Recipes for Enriched Naq, and Naquadria have some how snaked from NM into HM, only suppose to be able to get these resources via Naq line for Enriched Naq/Naquadria, or MK3 Fusion for Naquadria

**Comment by IntegerLimit** [comment]
Thanks!

**Comment by Folanlron** [comment]
- [ ] Fluid Drilling/Dilling Rigs don't seem to have recycling recipes on HM(Not sure on NM but I'm guessing that it works fine sense they don't have custom recipes), would be nice to have recycle recipes for at least Tier 1/2 Drilling/Fluid Rigs at least, not sure if tier 3 recipes really need one..

**Comment by IntegerLimit** [comment]
> * [ ]  Fluid Drilling/Dilling Rigs don't seem to have recycling recipes on HM(Not sure on NM but I'm guessing that it works fine sense they don't have custom recipes), would be nice to have recycle recipes for at least Tier 1/2 Drilling/Fluid Rigs at least, not sure if tier 3 recipes really need one..

Actually is a behaviour in vanilla GTCEu. Gonna leave without recycling for now, but, @Folanlron, can you move it to a seperate issue, to be discussed later?
