### ISSUE TITLE
(Initial) 1.7.4 TODO

### ISSUE THREAD

**Issue by IntegerLimit** [Nomi-CEu/Nomi-CEu#339]
- [ ] GT multi boilers are much worse than thermal's steam dynamo boilers (in both modes). Find a way to balance this.
- [x] Use Universal Tweaks, replace other mods with it (done in https://github.com/Nomi-CEu/Nomi-CEu/commit/7ca652d468166680fed9927c6dc2e4e0ca44f33e)
- [x] Add Vintage Fix when it releases (done in https://github.com/Nomi-CEu/Nomi-CEu/commit/7ca652d468166680fed9927c6dc2e4e0ca44f33e)
- [ ] Setup File Director for easy updates [maybe?]
- [x] Fix Hand Framing Tool refilling NPE (fixed in https://github.com/Nomi-CEu/Nomi-CEu/commit/4e4628f772419f2e44279d8a9603342618fd5524)

**Comment by IntegerLimit** [comment]
Interesting. Thank you for your observations.

**Comment by Folanlron** [comment]
> -.5 on the first bullet point. GT boilers seem to perform fine, slightly underpowered for cost, though. They end up being ~2-3 of the steam dynamo boilers, maybe making 1 multi roughly equal to 4 steam dynamo from thermal would be best. (requiring slightly more fuel or something) Unless boiler multis were changed since 1.5.2.
> 
> HM doesn't allow the usage of the steam->RF dynamo (whatever that upgrade is called) you _have_ to use the nomi steam turbines. The effectiveness is still questionable because of other factors, since I remember solar boilers being way better than the dynamos for no fuel cost.

No turbine Augment in HM, we can still make Boiler Augment and use that to feed a Steam Turbine till you can get Solar Boilers going, Also good for getting early into PE access as you can just use the direct output of the Steam Dynamo as the steam input for early Steam-Cracking. (that's how I did it in my current world, it all goes out the window once you get real Distillation going)

**Comment by IntegerLimit** [comment]
This is almost complete, except for the boiler issue. This is being fixed in 1.7.4.

**Comment by IntegerLimit** [comment]
Closing: This issue will be replaced by #677.
