### ISSUE TITLE
Buildscript & Wiki TODO

### ISSUE THREAD

**Issue by IntegerLimit** [Nomi-CEu/Nomi-CEu#459]
### Nomi CEu Version

1.6.1a

### Related Problem

N/A

### Your Solution

- [ ] Update Workflow Info in Wiki
- [ ] Create Installing and Updating page in Wiki
- [ ] Move Server Info to Wiki

- [ ] Create some sort of Mod List Info, for newest release, and beta/alpha if those are newer than release
- [ ] Create a cutting edge changelog, which is updated per commit, showing what has changed since latest release/alpha/beta

### How Will Your Solution Work

N/A

### Alternatives You've Considered

N/A

### Additional Information

N/A
