### ISSUE TITLE
1.7 TODO

### ISSUE THREAD

**Issue by IntegerLimit** [Nomi-CEu/Nomi-CEu#472]
### Nomi CEu Version

1.6.1a

### Related Problem

I'm always frustrated when I forget what to do.

### Your Solution

I could make a TODO! Yes me. I will make it happen, no need to like to have it happen.

### How Will Your Solution Work

Make an issue, thats a TODO!

### Alternatives You've Considered

Make a PR, thats a TODO!

### Additional Information

TODO:
- [x] Increase the amount of Neutronium from T9 Micro Miner
- [x] Decrease the amount of Iridium required for building Research setups (NM only)
- [x] Add JEI Descriptions for Various AE2 Items (Sticky Card...)
- [x] Add Betterer P2P
- [x] Update AE2 UEL
- [x] Move from AE2 Stuff to AE2 Stuff Unofficial
- [x] Update NAE2
- [ ] Update Alfheim when it is stable (1.2 is not stable)
- [x] Update Mixinbooter
- [x] Update Universal Tweaks
- [x] Update Vintage Fix
- [x] Update Other Mods
- [x] Update LoliASM

**Comment by v3ect0rgames** [comment]
It works if you 
Ae2 unofficial extended life to 0.56.6
Ae2stuff unofficial to 1.12.2-0.9
and delete the remove recipes for the old encoder on lines 163, 166 in AdvRocketry.zs

**Comment by v3ect0rgames** [comment]
Universal tweaks seems to work on 1.12.2-1.11.0

**Comment by v3ect0rgames** [comment]
Alfheim 1.3 seems to be stable

**Comment by v3ect0rgames** [comment]
Thats 3 things on the to-do list

**Comment by IntegerLimit** [comment]
> Alfheim 1.3 seems to be stable

It consumes a lot of ram, and thus we can't use it.

**Comment by IntegerLimit** [comment]
Also, everything is already confirmed to work, its just what needs to be done. However, thank you for your testing.

**Comment by v3ect0rgames** [comment]
ok thanks,  what alfheim version will be used then

**Comment by IntegerLimit** [comment]
> ok thanks, what alfheim version will be used then

The current version, it uses an appropriate amount of RAM.

**Comment by IntegerLimit** [comment]
This issue is now being closed, as Alfheim update uses too much memory for Nomi-CEu, and results in no improvements.
